version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  client:
    build: ./real-time-chat
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:4000
    depends_on:
      - server
    restart: unless-stopped